server:
  port: 3037
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?serverTimezone=Asia/Seoul
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
mail:
  address:
    admin: admin@gmail.com
